version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672 # porta para troca de mensagens 
      - 15672:15672 ## porta do gerenciador do rabbitmq
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      
volumes:
  rabbitmq:
